### ISSUE TITLE
update to work with node v4+

### ISSUE THREAD

**Issue by jonathanong** [isaacs/nosync#2]

**Comment by mk-pmb** [comment]
Tried to reproduce, but couldn't. Thus let me ask:
- What did you observe using it with node v4+?
- What did you expect instead?
- Which exact version(s) of node and this module did you test?
- How can others try to reproduce the problem?

My results:

```
$ node-versions

Node.js v6.1.0, npm v3.8.6, Ubuntu 14.04.5 LTS trusty

$ node -e "var fs = require('fs');
> setImmediate(function () {
>   var pkjs = fs.readFileSync('package.json', 'UTF-8');
>   pkjs = JSON.parse(pkjs);
>   console.log([pkjs.name, pkjs.version]);
> });"

[ 'nosync', '1.0.0' ]

$ node -e "var fs = require('fs');
> require('nosync');
> setImmediate(function () {
>   var pkjs = fs.readFileSync('package.json', 'UTF-8');
>   pkjs = JSON.parse(pkjs);
>   console.log([pkjs.name, pkjs.version]);
> });"                                                            

fs.js:725
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
[… snip …]
```

**Comment by mk-pmb** [comment]
Now it hit me as well. Interesting that the error only occurrs after the module was loaded successfully. Looking a bit harder, it seems to actually work as intended, just node.js itself does sync ops.

```text
$ nodever nosync
require('nosync/package.json').version = 1.0.0
Node.js v6.11.0, npm v4.4.0, Ubuntu 14.04.5 LTS trusty,
kernel: 3.13.0-119-generic, machine/CPU/platform: i686 i686 i686
$ nodejs -p 'var a = [ require("nosync") ]; a.concat("still alive!")'
[ {}, 'still alive!' ]
fs.js:732
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:732:19)
    at readline (/usr/lib/nodejs/internal/v8_prof_polyfill.js:76:22)
    at versionCheck (/usr/lib/nodejs/internal/v8_prof_polyfill.js:88:19)
    at Object.<anonymous> (/usr/lib/nodejs/internal/v8_prof_polyfill.js:67:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by mk-pmb** [comment]
Further testing reveals that it's not a default nodejs behavior though:

```bash
$ nodejs -p 'var fs = require("fs"); fs.readSync = null;'; echo rv=$?
null
rv=0
$ nodejs -p 'var fs = require("fs"); require("nosync"); fs.readSync = null;'; echo rv=$?
null
fs.js:487
    bytesRead = fs.readSync(fd, buffer, pos, len);
                   ^

TypeError: fs.readSync is not a function
    at tryReadSync (fs.js:487:20)
    at Object.fs.readFileSync (fs.js:527:19)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /mnt/basecamp/app-res/nodejs/modules/nosync/nosync.js:4:18
    at Array.map (native)
rv=1
```

More race condition research: https://gist.github.com/mk-pmb/9b4f3f47b3c769dc2b96437616fa72e0
